export enum IonIcons {
    home = 'home',
    login = 'log-in',
    register = 'download-outline',
    logout = 'log-out-outline',
    dashboard = 'stats-chart',
    more = 'ellipsis-vertical',
    user = 'person',
    forward = 'arrow-forward',
    circle_forward = 'arrow-forward-circle-outline',
    add = 'add-outline',
    remove = 'close-outline',
    show = 'eye-outline',
    hide = 'eye-off-outline',
    image = 'images-outline',
    trash = 'trash-outline',
    booking = 'calendar-outline',
    movie = 'laptop-outline',
    cinema = 'tv-outline',
    edit = 'create-outline',
    restore = 'file-tray-full-outline'
}